/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TSysUserRoleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSysUserRole extends TableImpl<TSysUserRoleRecord> {

    private static final long serialVersionUID = -1645321174;

    /**
     * The reference instance of <code>public.t_sys_user_role</code>
     */
    public static final TSysUserRole T_SYS_USER_ROLE = new TSysUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysUserRoleRecord> getRecordType() {
        return TSysUserRoleRecord.class;
    }

    /**
     * The column <code>public.t_sys_user_role.id</code>.
     */
    public final TableField<TSysUserRoleRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_sys_user_role.role_id</code>.
     */
    public final TableField<TSysUserRoleRecord, Long> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_sys_user_role.user_id</code>.
     */
    public final TableField<TSysUserRoleRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.t_sys_user_role</code> table reference
     */
    public TSysUserRole() {
        this(DSL.name("t_sys_user_role"), null);
    }

    /**
     * Create an aliased <code>public.t_sys_user_role</code> table reference
     */
    public TSysUserRole(String alias) {
        this(DSL.name(alias), T_SYS_USER_ROLE);
    }

    /**
     * Create an aliased <code>public.t_sys_user_role</code> table reference
     */
    public TSysUserRole(Name alias) {
        this(alias, T_SYS_USER_ROLE);
    }

    private TSysUserRole(Name alias, Table<TSysUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private TSysUserRole(Name alias, Table<TSysUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TSysUserRole(Table<O> child, ForeignKey<O, TSysUserRoleRecord> key) {
        super(child, key, T_SYS_USER_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_SYS_USER_ROLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TSysUserRoleRecord> getPrimaryKey() {
        return Keys.T_SYS_USER_ROLE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TSysUserRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<TSysUserRoleRecord>>asList(Keys.T_SYS_USER_ROLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSysUserRole as(String alias) {
        return new TSysUserRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSysUserRole as(Name alias) {
        return new TSysUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUserRole rename(String name) {
        return new TSysUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUserRole rename(Name name) {
        return new TSysUserRole(name, null);
    }
}
