/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.poem.jooq.Indexes;
import org.poem.jooq.Keys;
import org.poem.jooq.Public;
import org.poem.jooq.tables.records.TSysRolePermissionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSysRolePermission extends TableImpl<TSysRolePermissionRecord> {

    private static final long serialVersionUID = -1448709284;

    /**
     * The reference instance of <code>public.t_sys_role_permission</code>
     */
    public static final TSysRolePermission T_SYS_ROLE_PERMISSION = new TSysRolePermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysRolePermissionRecord> getRecordType() {
        return TSysRolePermissionRecord.class;
    }

    /**
     * The column <code>public.t_sys_role_permission.id</code>.
     */
    public final TableField<TSysRolePermissionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_sys_role_permission.permission_id</code>.
     */
    public final TableField<TSysRolePermissionRecord, Long> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_sys_role_permission.role_id</code>.
     */
    public final TableField<TSysRolePermissionRecord, Long> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.t_sys_role_permission</code> table reference
     */
    public TSysRolePermission() {
        this(DSL.name("t_sys_role_permission"), null);
    }

    /**
     * Create an aliased <code>public.t_sys_role_permission</code> table reference
     */
    public TSysRolePermission(String alias) {
        this(DSL.name(alias), T_SYS_ROLE_PERMISSION);
    }

    /**
     * Create an aliased <code>public.t_sys_role_permission</code> table reference
     */
    public TSysRolePermission(Name alias) {
        this(alias, T_SYS_ROLE_PERMISSION);
    }

    private TSysRolePermission(Name alias, Table<TSysRolePermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TSysRolePermission(Name alias, Table<TSysRolePermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TSysRolePermission(Table<O> child, ForeignKey<O, TSysRolePermissionRecord> key) {
        super(child, key, T_SYS_ROLE_PERMISSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_SYS_ROLE_PERMISSION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TSysRolePermissionRecord> getPrimaryKey() {
        return Keys.T_SYS_ROLE_PERMISSION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TSysRolePermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<TSysRolePermissionRecord>>asList(Keys.T_SYS_ROLE_PERMISSION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSysRolePermission as(String alias) {
        return new TSysRolePermission(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSysRolePermission as(Name alias) {
        return new TSysRolePermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRolePermission rename(String name) {
        return new TSysRolePermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRolePermission rename(Name name) {
        return new TSysRolePermission(name, null);
    }
}
