/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.poem.jooq.tables.TSysPermission;
import org.poem.jooq.tables.TSysRole;
import org.poem.jooq.tables.TSysRolePermission;
import org.poem.jooq.tables.TSysUserRole;
import org.poem.jooq.tables.TUserInfo;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_SYS_PERMISSION_PKEY = Indexes0.T_SYS_PERMISSION_PKEY;
    public static final Index T_SYS_ROLE_PKEY = Indexes0.T_SYS_ROLE_PKEY;
    public static final Index T_SYS_ROLE_PERMISSION_PKEY = Indexes0.T_SYS_ROLE_PERMISSION_PKEY;
    public static final Index T_SYS_USER_ROLE_PKEY = Indexes0.T_SYS_USER_ROLE_PKEY;
    public static final Index T_USER_INFO_PKEY = Indexes0.T_USER_INFO_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_SYS_PERMISSION_PKEY = Internal.createIndex("t_sys_permission_pkey", TSysPermission.T_SYS_PERMISSION, new OrderField[] { TSysPermission.T_SYS_PERMISSION.ID }, true);
        public static Index T_SYS_ROLE_PKEY = Internal.createIndex("t_sys_role_pkey", TSysRole.T_SYS_ROLE, new OrderField[] { TSysRole.T_SYS_ROLE.ID }, true);
        public static Index T_SYS_ROLE_PERMISSION_PKEY = Internal.createIndex("t_sys_role_permission_pkey", TSysRolePermission.T_SYS_ROLE_PERMISSION, new OrderField[] { TSysRolePermission.T_SYS_ROLE_PERMISSION.ID }, true);
        public static Index T_SYS_USER_ROLE_PKEY = Internal.createIndex("t_sys_user_role_pkey", TSysUserRole.T_SYS_USER_ROLE, new OrderField[] { TSysUserRole.T_SYS_USER_ROLE.ID }, true);
        public static Index T_USER_INFO_PKEY = Internal.createIndex("t_user_info_pkey", TUserInfo.T_USER_INFO, new OrderField[] { TUserInfo.T_USER_INFO.ID }, true);
    }
}
