/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq;


import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.poem.jooq.tables.TSysPermission;
import org.poem.jooq.tables.TSysRole;
import org.poem.jooq.tables.TSysRolePermission;
import org.poem.jooq.tables.TSysUserRole;
import org.poem.jooq.tables.TUserInfo;
import org.poem.jooq.tables.records.TSysPermissionRecord;
import org.poem.jooq.tables.records.TSysRolePermissionRecord;
import org.poem.jooq.tables.records.TSysRoleRecord;
import org.poem.jooq.tables.records.TSysUserRoleRecord;
import org.poem.jooq.tables.records.TUserInfoRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TSysPermissionRecord> T_SYS_PERMISSION_PKEY = UniqueKeys0.T_SYS_PERMISSION_PKEY;
    public static final UniqueKey<TSysRoleRecord> T_SYS_ROLE_PKEY = UniqueKeys0.T_SYS_ROLE_PKEY;
    public static final UniqueKey<TSysRolePermissionRecord> T_SYS_ROLE_PERMISSION_PKEY = UniqueKeys0.T_SYS_ROLE_PERMISSION_PKEY;
    public static final UniqueKey<TSysUserRoleRecord> T_SYS_USER_ROLE_PKEY = UniqueKeys0.T_SYS_USER_ROLE_PKEY;
    public static final UniqueKey<TUserInfoRecord> T_USER_INFO_PKEY = UniqueKeys0.T_USER_INFO_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TSysPermissionRecord> T_SYS_PERMISSION_PKEY = Internal.createUniqueKey(TSysPermission.T_SYS_PERMISSION, "t_sys_permission_pkey", TSysPermission.T_SYS_PERMISSION.ID);
        public static final UniqueKey<TSysRoleRecord> T_SYS_ROLE_PKEY = Internal.createUniqueKey(TSysRole.T_SYS_ROLE, "t_sys_role_pkey", TSysRole.T_SYS_ROLE.ID);
        public static final UniqueKey<TSysRolePermissionRecord> T_SYS_ROLE_PERMISSION_PKEY = Internal.createUniqueKey(TSysRolePermission.T_SYS_ROLE_PERMISSION, "t_sys_role_permission_pkey", TSysRolePermission.T_SYS_ROLE_PERMISSION.ID);
        public static final UniqueKey<TSysUserRoleRecord> T_SYS_USER_ROLE_PKEY = Internal.createUniqueKey(TSysUserRole.T_SYS_USER_ROLE, "t_sys_user_role_pkey", TSysUserRole.T_SYS_USER_ROLE.ID);
        public static final UniqueKey<TUserInfoRecord> T_USER_INFO_PKEY = Internal.createUniqueKey(TUserInfo.T_USER_INFO, "t_user_info_pkey", TUserInfo.T_USER_INFO.ID);
    }
}
