/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.poem.jooq.tables.TSysPermission;
import org.poem.jooq.tables.TSysRole;
import org.poem.jooq.tables.TSysRolePermission;
import org.poem.jooq.tables.TSysUserRole;
import org.poem.jooq.tables.TUserInfo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1855210881;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.t_sys_permission</code>.
     */
    public final TSysPermission T_SYS_PERMISSION = org.poem.jooq.tables.TSysPermission.T_SYS_PERMISSION;

    /**
     * The table <code>public.t_sys_role</code>.
     */
    public final TSysRole T_SYS_ROLE = org.poem.jooq.tables.TSysRole.T_SYS_ROLE;

    /**
     * The table <code>public.t_sys_role_permission</code>.
     */
    public final TSysRolePermission T_SYS_ROLE_PERMISSION = org.poem.jooq.tables.TSysRolePermission.T_SYS_ROLE_PERMISSION;

    /**
     * The table <code>public.t_sys_user_role</code>.
     */
    public final TSysUserRole T_SYS_USER_ROLE = org.poem.jooq.tables.TSysUserRole.T_SYS_USER_ROLE;

    /**
     * The table <code>public.t_user_info</code>.
     */
    public final TUserInfo T_USER_INFO = org.poem.jooq.tables.TUserInfo.T_USER_INFO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TSysPermission.T_SYS_PERMISSION,
            TSysRole.T_SYS_ROLE,
            TSysRolePermission.T_SYS_ROLE_PERMISSION,
            TSysUserRole.T_SYS_USER_ROLE,
            TUserInfo.T_USER_INFO);
    }
}
