/*
 * This file is generated by jOOQ.
 */
package org.poem.jooq;


import javax.annotation.Generated;

import org.poem.jooq.tables.TSysPermission;
import org.poem.jooq.tables.TSysRole;
import org.poem.jooq.tables.TSysRolePermission;
import org.poem.jooq.tables.TSysUserRole;
import org.poem.jooq.tables.TUserInfo;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.t_sys_permission</code>.
     */
    public static final TSysPermission T_SYS_PERMISSION = TSysPermission.T_SYS_PERMISSION;

    /**
     * The table <code>public.t_sys_role</code>.
     */
    public static final TSysRole T_SYS_ROLE = TSysRole.T_SYS_ROLE;

    /**
     * The table <code>public.t_sys_role_permission</code>.
     */
    public static final TSysRolePermission T_SYS_ROLE_PERMISSION = TSysRolePermission.T_SYS_ROLE_PERMISSION;

    /**
     * The table <code>public.t_sys_user_role</code>.
     */
    public static final TSysUserRole T_SYS_USER_ROLE = TSysUserRole.T_SYS_USER_ROLE;

    /**
     * The table <code>public.t_user_info</code>.
     */
    public static final TUserInfo T_USER_INFO = TUserInfo.T_USER_INFO;
}
